const { app, BrowserWindow, Menu } = require('electron');
const fs = require('node:fs'), os = require('node:os'), path = require('node:path'), assert = require('node:assert/strict');
const scratch = fs.mkdtempSync(path.join(os.tmpdir(), 'neo-menu-test-'));
const device = path.join(scratch, 'device'), libraryDir = path.join(scratch, 'books');
fs.mkdirSync(device); fs.mkdirSync(path.join(libraryDir, 'book-one', 'chapters'), { recursive: true });
fs.writeFileSync(path.join(device, 'settings.json'), JSON.stringify({ libraryDir }));
fs.writeFileSync(path.join(libraryDir, 'library.json'), JSON.stringify({ firstRunDone: true, authorName: 'Fixture', hintShown: true, coverArt: { auto: false }, shelves: [{ id: 'shelf', name: 'Books', bookIds: ['book-one'] }] }));
fs.writeFileSync(path.join(libraryDir, 'book-one', 'book.json'), JSON.stringify({ id: 'book-one', title: 'Menu fixture', chapterOrder: ['ch-one'], workspaceTree: { characters: [{ id: 'character', type: 'document', title: 'Detective', text: '<p>A patient detective.</p>' }] } }));
fs.writeFileSync(path.join(libraryDir, 'book-one', 'chapters', 'ch-one.html'), '<p>The detective arrived.</p>');
app.setPath('userData', device); process.env.NEO_TEST_HEADLESS = '1';
require(process.env.NEO_MENUS_PACKAGED ? '../dist/win-unpacked/resources/app.asar/main.js' : '../main');
const pause = ms => new Promise(resolve => setTimeout(resolve, ms));
const evaluate = (win, code) => win.webContents.executeJavaScript(code, true);
const items = menu => menu.items.flatMap(item => [item, ...(item.submenu ? items(item.submenu) : [])]);
const command = type => items(Menu.getApplicationMenu()).find(item => item.id?.startsWith('action:' + type + ':'));
const label = name => items(Menu.getApplicationMenu()).find(item => item.label === name);
const find = file => BrowserWindow.getAllWindows().find(win => win.webContents.getURL().endsWith('/' + file));
async function until(fn, name) { const end = Date.now() + 15000; while (Date.now() < end) { if (await fn()) return; await pause(50); } throw new Error('Timed out: ' + name); }
const errors = [];
app.on('web-contents-created', (_event, wc) => wc.on('console-message', event => { if (event.level === 'error') errors.push(event.message); }));
app.whenReady().then(async () => {
  await until(() => find('index.html'), 'workspace'); const owner = find('index.html');
  await until(() => command('import')?.enabled, 'menus loaded');
  assert.equal(command('export').enabled, false); assert.equal(command('searchBook').enabled, false);
  assert.equal(label('Format').enabled, false); assert.equal(label('About Neo-AI').enabled, true);
  assert.equal(label('Brighter Interface'), undefined); assert.equal(label('NEO Shortcuts'), undefined);
  const accelerators = items(Menu.getApplicationMenu()).filter(item => item.accelerator).map(item => item.accelerator);
  assert.equal(new Set(accelerators).size, accelerators.length, 'duplicate accelerators');
  label('Settings…').click(); await until(() => find('settings.html'), 'settings');
  const settings = find('settings.html');
  await until(() => evaluate(settings, '!document.querySelector("#general").hidden'), 'Settings opens General');
  await evaluate(settings, 'document.querySelector("[data-page=ai]").click()');
  label('Appearance…').click(); await until(() => evaluate(settings, '!document.querySelector("#general").hidden'), 'Appearance opens General');
  settings.close(); await until(() => !find('settings.html'), 'settings closed');
  owner.show(); owner.focus(); await evaluate(owner, 'openBook("book-one")');
  await until(() => command('export').enabled && command('bodyFont').enabled, 'book commands');
  await evaluate(owner, `(() => { const e=document.querySelector('.chapter-body'); e.focus(); const range=document.createRange();range.selectNodeContents(e.querySelector('p')); const selection=getSelection();selection.removeAllRanges();selection.addRange(range); })()`);
  await until(() => command('align').enabled && command('poetry').enabled, 'manuscript selection');
  label('Center').click(); await until(() => evaluate(owner, 'getComputedStyle(document.querySelector(".chapter-body p")).textAlign === "center"'), 'manuscript alignment');
  await evaluate(owner, 'document.execCommand("undo")');
  await until(() => evaluate(owner, 'getComputedStyle(document.querySelector(".chapter-body p")).textAlign !== "center"'), 'alignment Undo');
  await evaluate(owner, 'openWorkspaceNode("characters","character")');
  await until(() => !command('bodyFont').enabled, 'reference scope');
  await evaluate(owner, `(() => { const e=document.querySelector('.tree-document-text');e.focus(); const r=document.createRange();r.selectNodeContents(e);const s=getSelection();s.removeAllRanges();s.addRange(r); })()`);
  await until(() => command('align').enabled, 'reference selection'); assert.equal(command('poetry').enabled, false);
  label('Center').click(); await until(() => evaluate(owner, 'document.queryCommandState("justifyCenter")'), 'reference alignment');
  await evaluate(owner, 'document.execCommand("undo")');
  await until(() => evaluate(owner, '!document.queryCommandState("justifyCenter")'), 'reference Undo');
  label('Keyboard Shortcuts…').click(); await until(() => evaluate(owner, '!!document.querySelector("#keyboard-shortcuts")'), 'shortcuts');
  await until(() => !command('export').enabled, 'modal guard');
  assert.equal(await evaluate(owner, 'document.querySelector("#keyboard-shortcuts").textContent.includes("Settings")'), true);
  await evaluate(owner, 'document.querySelector("#keyboard-shortcuts .m-ok").click()');
  await until(() => command('export').enabled, 'modal closed');
  command('about').click(); await until(() => evaluate(owner, '!!document.querySelector("#app-about")'), 'about');
  assert.match(await evaluate(owner, 'document.querySelector("#app-about").textContent'), /Neo-AI/);
  await pause(400);
  fs.writeFileSync(path.join(scratch, 'about.png'), (await owner.webContents.capturePage()).toPNG());
  await evaluate(owner, 'document.querySelector("#app-about .m-ok").click()');
  // A separate window must never apply Format commands to the hidden selection.
  await evaluate(owner, 'detachOutline()'); await until(() => find('pane.html'), 'outline'); const pane = find('pane.html');
  pane.show(); pane.focus(); await until(() => BrowserWindow.getFocusedWindow() === pane, 'pane focus');
  await until(() => !command('align').enabled && !command('searchBook').enabled, 'pane guard');
  owner.show(); owner.focus(); await until(() => command('searchBook').enabled, 'owner focus');
  owner.webContents.focus();
  if (process.platform === 'darwin') {
    // NSMenu needs a native NSEvent, which sendInputEvent does not create.
    assert.equal(command('searchBook').accelerator, 'Command+Shift+F');
    command('searchBook').click();
  } else {
    owner.webContents.sendInputEvent({ type: 'keyDown', keyCode: 'F', modifiers: [process.platform === 'darwin' ? 'meta' : 'control', 'shift'] });
    owner.webContents.sendInputEvent({ type: 'keyUp', keyCode: 'F', modifiers: [process.platform === 'darwin' ? 'meta' : 'control', 'shift'] });
  }
  await until(() => evaluate(owner, 'document.querySelector("#book-search-dialog").open'), 'search accelerator');
  assert.equal(owner.isFullScreen(), false);
  await evaluate(owner, 'document.querySelector("#book-search-close").click()');
  label('Full Screen').click(); await until(() => owner.isFullScreen(), 'full screen'); owner.setFullScreen(false);
  await until(() => !owner.isFullScreen(), 'leave fullscreen');
  await evaluate(owner, 'backToShelf()'); await until(() => !command('export').enabled, 'bookshelf guard');
  assert.deepEqual(errors, []);
  console.log('PASS: menu scopes, focus, dialogs, Settings routes, labels, shortcuts, and alignment with Undo. Screenshots: ' + scratch); app.exit(0);
}).catch(error => { console.error(error); console.error(errors); app.exit(1); });
setTimeout(() => { console.error('Menu test timed out'); app.exit(1); }, 90000).unref();
