const { app, BrowserWindow, Menu } = require('electron');
const fs = require('node:fs'), path = require('node:path'), os = require('node:os'), assert = require('node:assert/strict');
const scratch = fs.mkdtempSync(path.join(os.tmpdir(), 'neo-ai-search-'));
const device = path.join(scratch, 'device'), libraryDir = path.join(scratch, 'library');
fs.mkdirSync(device); fs.mkdirSync(path.join(libraryDir, 'book-one', 'chapters'), { recursive: true });
fs.writeFileSync(path.join(device, 'settings.json'), JSON.stringify({ libraryDir }));
fs.writeFileSync(path.join(libraryDir, 'library.json'), JSON.stringify({ firstRunDone: true, pageTheme: 'night', authorName: 'Fixture', hintShown: true, coverArt: { auto: false }, shelves: [{ id: 'shelf', name: 'Works in progress', bookIds: ['book-one'] }] }));
fs.writeFileSync(path.join(libraryDir, 'book-one', 'book.json'), JSON.stringify({ id: 'book-one', title: 'Under the Stars', author: 'Fixture', chapterOrder: ['ch-one'], workspaceTree: { characters: [{ id: 'card', type: 'document', title: 'Elara', text: 'A character reference.' }] } }));
fs.writeFileSync(path.join(libraryDir, 'book-one', 'chapters', 'ch-one.html'), '<p>A scene under the stars.</p>');
fs.writeFileSync(path.join(libraryDir, 'book-one', 'ai-chats.json'), JSON.stringify({ version: 1, selectedId: 'chat-one', conversations: [{ id: 'chat-one', title: 'Character ideas', draft: '', contextIds: [], messages: [{ id: 'prompt', role: 'user', content: 'Suggest a detail about Elara.', status: 'complete' }, { id: 'reply', role: 'assistant', content: '### A suggestion\n\n**Elara** keeps a journal.\n\n- A place for memories\n- A reminder of her goals', status: 'complete' }] }] }));
fs.mkdirSync(path.join(libraryDir, 'book-two', 'chapters'), { recursive: true });
fs.writeFileSync(path.join(libraryDir, 'book-two', 'book.json'), JSON.stringify({ id: 'book-two', title: 'Other book', chapterOrder: [] }));
app.setPath('userData', device); process.env.NEO_TEST_HEADLESS = '1';
const errors = [];
app.on('web-contents-created', (_event, wc) => wc.on('console-message', event => { if (event.level === 'error') errors.push(event.message); }));
require('../main');
const pause = ms => new Promise(resolve => setTimeout(resolve, ms));
const evaluate = (win, code) => win.webContents.executeJavaScript(code, true);
async function until(fn, label) { const end = Date.now() + 12000; while (Date.now() < end) { if (await fn()) return; await pause(40); } throw new Error('Timed out: ' + label); }
const find = file => BrowserWindow.getAllWindows().find(win => win.webContents.getURL().endsWith('/' + file));
async function screenshot(win, name) { win.showInactive(); await pause(500); fs.writeFileSync(path.join(scratch, name + '.png'), (await win.webContents.capturePage()).toPNG()); win.hide(); }
app.whenReady().then(async () => {
  await until(() => find('index.html'), 'owner'); const owner = find('index.html'); owner.setSize(1400, 1000);
  await until(() => evaluate(owner, 'typeof library !== "undefined" && !!library'), 'startup');
  await evaluate(owner, 'openBook("book-one")');
  await until(() => evaluate(owner, '!!window.openBookSearch'), 'search ready');
  await evaluate(owner, `book.workspaceTree.notes.push({id:'note',type:'document',title:'Test note',text:'A journal in the forest.'});book.workspaceTree.darlings.push({id:'cut',type:'document',title:'Saved passage',text:'Journal of a journey.'});book.workspaceTree.characters[0].aiContext=false`);
  await evaluate(owner, 'openWorkspaceNode("characters","card")');
  await evaluate(owner, `(() => {const editor=document.querySelector('.tree-document-text');editor.innerHTML='<p>A <b>journal</b> with &lt;img src=x onerror=alert(1)&gt;.</p>';editor.dispatchEvent(new Event('input',{bubbles:true}))})()`);
  async function query(text, scope='') {
    await evaluate(owner, 'window.openBookSearch()');
    await evaluate(owner, `(() => {document.querySelector('#book-search-query').value=${JSON.stringify(text)};const scope=document.querySelector('#book-search-section');scope.value=${JSON.stringify(scope)};scope.dispatchEvent(new Event('change'))})()`);
  }
  const count = () => evaluate(owner, 'document.querySelectorAll(".book-search-result").length');
  await query('journal'); assert.equal(await count(), 4, await evaluate(owner, 'document.querySelector("#book-search-dialog").textContent'));
  assert.equal(await evaluate(owner, 'document.querySelectorAll("#book-search-results img").length'), 0);
  assert.ok(await evaluate(owner, 'document.querySelectorAll("#book-search-results mark").length > 0'));
  await screenshot(owner, 'search-results');
  await query('journal','characters'); assert.equal(await count(), 1);
  await evaluate(owner, 'document.querySelector(".book-search-result").click()');
  await until(() => evaluate(owner, '!document.querySelector("#book-search-dialog").open && workspaceSelection?.id === "card"'), 'document navigation');
  await query('[a.*]'); assert.equal(await count(), 0);
  await query('under the stars', 'manuscript'); assert.equal(await count(), 1);
  await evaluate(owner, 'document.querySelector(".book-search-result").click()');
  await until(() => evaluate(owner, 'currentTab === "manuscript" && currentChapterId === "ch-one"'), 'manuscript navigation');
  await query('journal', 'ai-assistance'); assert.equal(await count(), 1);
  await evaluate(owner, 'document.querySelector(".book-search-result").click()');
  await until(() => evaluate(owner, 'window.neoChatView.current()?.id === "chat-one" && !!document.querySelector(".ai-search-match")'), 'chat message navigation');
  assert.equal(await evaluate(owner, 'document.querySelector(".ai-search-match").dataset.messageId'), 'reply');
  await evaluate(owner, 'window.neoChatView.detachButton.click()'); await until(() => find('ai-pane.html'), 'detached chat'); const chat = find('ai-pane.html');
  await until(() => evaluate(chat, 'view.current()?.id === "chat-one"'), 'detached chat loaded');
  await evaluate(chat, 'view.draft.value="Keep this unsent draft";view.draft.dispatchEvent(new Event("input"))');
  await query('journal', 'ai-assistance'); await evaluate(owner, 'document.querySelector(".book-search-result").click()');
  await until(() => evaluate(chat, '!!document.querySelector(".ai-search-match")'), 'detached message revealed');
  assert.equal(await evaluate(chat, 'view.draft.value'), 'Keep this unsent draft');
  // Reopen uses the latest document state and does not send anything to AI.
  await evaluate(owner, 'openWorkspaceNode("notes","note")');
  await evaluate(owner, `(() => {const editor=document.querySelector('.tree-document-text');editor.textContent='Fresh replacement';editor.dispatchEvent(new Event('input',{bubbles:true}))})()`);
  await query('Fresh replacement'); assert.equal(await count(), 1);
  await query('journal', 'notes'); assert.equal(await count(), 0);
  await evaluate(owner, 'document.querySelector("#book-search-close").click()');
  owner.show(); owner.focus(); owner.webContents.focus();
  const searchMenu = Menu.getApplicationMenu().items.flatMap(item => item.submenu?.items || []).find(item => item.label === 'Search Book…');
  await until(() => searchMenu.enabled, 'search menu available in focused workspace');
  assert.equal(searchMenu.accelerator, 'CmdOrCtrl+Shift+F'); searchMenu.click();
  await until(() => evaluate(owner, 'document.querySelector("#book-search-dialog").open'), 'search shortcut menu');
  await evaluate(owner, 'document.querySelector("#book-search-close").click()');
  const allItems = menu => menu.items.flatMap(item => [item, ...(item.submenu ? allItems(item.submenu) : [])]);
  assert.equal(allItems(Menu.getApplicationMenu()).filter(item => item.accelerator === 'CmdOrCtrl+Shift+F').length, 1);
  owner.show(); owner.focus(); owner.webContents.focus();
  await until(() => searchMenu.enabled, 'search keyboard shortcut available');
  const modifiers = [process.platform === 'darwin' ? 'meta' : 'control', 'shift'];
  owner.webContents.sendInputEvent({ type: 'keyDown', keyCode: 'F', modifiers });
  owner.webContents.sendInputEvent({ type: 'keyUp', keyCode: 'F', modifiers });
  await until(() => evaluate(owner, 'document.querySelector("#book-search-dialog").open'), 'actual search key combination');
  assert.equal(owner.isFullScreen(), false);
  await evaluate(owner, 'document.querySelector("#book-search-close").click()');
  const fullKey = process.platform === 'darwin' ? 'F' : 'F11';
  const fullModifiers = process.platform === 'darwin' ? ['control', 'meta'] : [];
  owner.webContents.sendInputEvent({ type: 'keyDown', keyCode: fullKey, modifiers: fullModifiers });
  owner.webContents.sendInputEvent({ type: 'keyUp', keyCode: fullKey, modifiers: fullModifiers });
  await until(() => owner.isFullScreen(), 'fullscreen shortcut');
  owner.setFullScreen(false); await until(() => !owner.isFullScreen(), 'exit fullscreen'); owner.hide();
  await evaluate(owner, 'openBook("book-two")');
  await query('journal'); assert.equal(await count(), 0);
  assert.equal(await evaluate(owner, 'document.querySelector("#book-search-description").textContent'), 'Other book');
  await evaluate(owner, 'document.querySelector("#book-search-query").value="";document.querySelector("#book-search-section").dispatchEvent(new Event("change"))');
  assert.equal(await count(), 0);
  assert.deepEqual(errors, []);
  console.log('PASS: live edits, literal search, all sections, safe previews, manuscript/reference/chat navigation, detached chat, draft preservation, real keyboard search/fullscreen shortcuts and book isolation.');
  console.log('Screenshots: '+scratch); app.exit(0);
}).catch(error => { console.error(error); console.error(errors); app.exit(1); });
setTimeout(() => { console.error('Search test timed out'); app.exit(1); }, 90000).unref();
